//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgricultureDetailView
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public System.DateTime Createdt { get; set; }
        public string MarketName { get; set; }
        public string UnitName { get; set; }
        public Nullable<double> Price { get; set; }
        public string CreateDay { get; set; }
    }
}
