//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityService.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CityServiceModelContainer : DbContext
    {
        public CityServiceModelContainer()
            : base("name=CityServiceModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TravalSpotView> TravalSpotView { get; set; }
        public DbSet<TravalSpotDetailView> TravalSpotDetailView { get; set; }
        public DbSet<TravalPlaceView> TravalPlaceView { get; set; }
        public DbSet<TravalPlaceDetail> TravalPlaceDetail { get; set; }
        public DbSet<AgricultureDetailView> AgricultureDetailView { get; set; }
        public DbSet<AgricultureMarket> AgricultureMarket { get; set; }
        public DbSet<AgricultureParticiple> AgricultureParticiple { get; set; }
        public DbSet<SchoolDistrict> SchoolDistrict { get; set; }
        public DbSet<Depart> Depart { get; set; }
        public DbSet<Doctor> Doctor { get; set; }
        public DbSet<Hospital> Hospital { get; set; }
        public DbSet<schedual> schedual { get; set; }
        public DbSet<Member> Member { get; set; }
        public DbSet<Register> Register { get; set; }
        public DbSet<ZWBST_ShfwzList> ZWBST_ShfwzList { get; set; }
        public DbSet<ZWBST_EntDetail> ZWBST_EntDetail { get; set; }
        public DbSet<ZWBST_EntSfbz> ZWBST_EntSfbz { get; set; }
    }
}
