//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZWBST_EntSfbz
    {
        public string GUID { get; set; }
        public string ENTERPRICEGUID { get; set; }
        public string TYPE { get; set; }
        public string NAME { get; set; }
        public string UNIT { get; set; }
        public string PRICE1 { get; set; }
        public string PRICE2 { get; set; }
        public string REMARK { get; set; }
        public string REMARK1 { get; set; }
    }
}
