//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZWBST_EntDetail
    {
        public string GUID { get; set; }
        public string ENTERPRICENAME { get; set; }
        public string LOGO { get; set; }
        public string ENTERPRICEINFO { get; set; }
        public string ADDRESS { get; set; }
        public string CONTACT { get; set; }
        public string JYFW { get; set; }
        public string TJNR { get; set; }
        public string FWCL { get; set; }
        public string FWQYFW { get; set; }
    }
}
