//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityService.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZWBST_ShfwzList
    {
        public int ID { get; set; }
        public string GUID { get; set; }
        public string SERVICETYPEGUID { get; set; }
        public string SERVICENAME { get; set; }
        public string ENTERPRICEGUID { get; set; }
        public string ENTERPRICENAME { get; set; }
    }
}
