//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36279
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityService.Service.EhrServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.ws.com/", ConfigurationName="EhrServiceReference.EhrService")]
    public interface EhrService {
        
        // CODEGEN: 命名空间  的元素名称 GetCheckRptReq 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CityService.Service.EhrServiceReference.ehrServiceResponse ehrService(CityService.Service.EhrServiceReference.ehrService1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CityService.Service.EhrServiceReference.ehrServiceResponse> ehrServiceAsync(CityService.Service.EhrServiceReference.ehrService1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ehrService1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ehrService", Namespace="http://service.ws.com/", Order=0)]
        public CityService.Service.EhrServiceReference.ehrService1Body Body;
        
        public ehrService1() {
        }
        
        public ehrService1(CityService.Service.EhrServiceReference.ehrService1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ehrService1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCheckRptReq;
        
        public ehrService1Body() {
        }
        
        public ehrService1Body(string GetCheckRptReq) {
            this.GetCheckRptReq = GetCheckRptReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ehrServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ehrServiceResponse", Namespace="http://service.ws.com/", Order=0)]
        public CityService.Service.EhrServiceReference.ehrServiceResponseBody Body;
        
        public ehrServiceResponse() {
        }
        
        public ehrServiceResponse(CityService.Service.EhrServiceReference.ehrServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ehrServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ehrServiceResponseBody() {
        }
        
        public ehrServiceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EhrServiceChannel : CityService.Service.EhrServiceReference.EhrService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EhrServiceClient : System.ServiceModel.ClientBase<CityService.Service.EhrServiceReference.EhrService>, CityService.Service.EhrServiceReference.EhrService {
        
        public EhrServiceClient() {
        }
        
        public EhrServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EhrServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EhrServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EhrServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CityService.Service.EhrServiceReference.ehrServiceResponse CityService.Service.EhrServiceReference.EhrService.ehrService(CityService.Service.EhrServiceReference.ehrService1 request) {
            return base.Channel.ehrService(request);
        }
        
        public string ehrService(string GetCheckRptReq) {
            CityService.Service.EhrServiceReference.ehrService1 inValue = new CityService.Service.EhrServiceReference.ehrService1();
            inValue.Body = new CityService.Service.EhrServiceReference.ehrService1Body();
            inValue.Body.GetCheckRptReq = GetCheckRptReq;
            CityService.Service.EhrServiceReference.ehrServiceResponse retVal = ((CityService.Service.EhrServiceReference.EhrService)(this)).ehrService(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CityService.Service.EhrServiceReference.ehrServiceResponse> CityService.Service.EhrServiceReference.EhrService.ehrServiceAsync(CityService.Service.EhrServiceReference.ehrService1 request) {
            return base.Channel.ehrServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CityService.Service.EhrServiceReference.ehrServiceResponse> ehrServiceAsync(string GetCheckRptReq) {
            CityService.Service.EhrServiceReference.ehrService1 inValue = new CityService.Service.EhrServiceReference.ehrService1();
            inValue.Body = new CityService.Service.EhrServiceReference.ehrService1Body();
            inValue.Body.GetCheckRptReq = GetCheckRptReq;
            return ((CityService.Service.EhrServiceReference.EhrService)(this)).ehrServiceAsync(inValue);
        }
    }
}
